services:
  city-street-data:
    build:
      context: .
      args:
        SQLITE_DB: ${SQLITE_DB}
        CHRON_HOME: ${CHRON_HOME}
    container_name: city-street-data
    hostname: city-street-data
    command: bash -c "
      . /opt/chron_venv/bin/activate;
      nohup python3 ./datapipeline/chronjobs/main.py -j sf_open_data_local_load >> ./datapipeline/chronjobs/sf_open_data_local_load.out &&
      nohup python3 ./datapipeline/chronjobs/main.py -j sf_open_data_api_load >> ./datapipeline/chronjobs/sf_open_data_api_load.out;
      deactivate;
      cd /backend && air -c .air.toml;"
    ports:
      - 80:8080
      - 8080:8081
    environment:
      - PROJ_DIR=${PROJ_DIR}
      - SQLITE_DB=${SQLITE_DB}
      - CHRON_HOME=${CHRON_HOME}
      - SF_DATA_APP_TOKEN=${SF_DATA_APP_TOKEN}
    volumes:
      - ./frontend:/frontend
      - ./backend:/backend
      - ./datapipeline/chronjobs:${CHRON_HOME}
    deploy:
      restart_policy:
        condition: on-failure
