CREATE TABLE sf_intersection_level_traffic_calming_devices_{suffix} (
    row_id NUMERIC,
    objectid NUMERIC,
    cnn NUMERIC,
    streetname TEXT,
    project_lo TEXT,
    from_st TEXT,
    tc_measure TEXT,
    units NUMERIC,
    install_mo NUMERIC,
    install_yr NUMERIC,
    install_date TIMESTAMP,
    fiscal_yr TEXT,
    program TEXT,
    current_status TEXT,
    supervisor_district VARCHAR(32),
    analysis_neighborhood TEXT,
    shape geometry(Point, 4326),
    data_as_of TIMESTAMP,
    data_loaded_at TIMESTAMP
);