DROP TABLE IF EXISTS sf_pd_incident_reports_2018_to_present_{suffix};
CREATE TABLE sf_pd_incident_reports_2018_to_present_{suffix} (
    row_id BIGINT,
    incident_datetime TIMESTAMP,
    incident_date DATE,
    incident_time VARCHAR(8),
    incident_year SMALLINT,
    incident_day_of_week TEXT,
    report_datetime TIMESTAMP,
    incident_id INTEGER,
    incident_number INTEGER,
    cad_number NUMERIC,
    report_type_code VARCHAR,
    report_type_description TEXT,
    filed_online BOOLEAN,
    incident_code TEXT,
    incident_category TEXT,
    incident_subcategory TEXT,
    incident_description TEXT,
    resolution TEXT,
    intersection TEXT,
    cnn NUMERIC,
    police_district TEXT,
    analysis_neighborhood TEXT,
    supervisor_district TEXT,
    supervisor_district_2012 TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    point geometry(Point, 4326),
    data_as_of TIMESTAMP,
    data_loaded_at TIMESTAMP
);
