CREATE TABLE sf_slow_streets_{suffix} (
    objectid NUMERIC,
    shape geometry(LineString, 4326),
    classcode NUMERIC,
    cnn NUMERIC,
    f_node_cnn NUMERIC,
    f_st TEXT,
    nhood TEXT,
    oneway VARCHAR(4),
    st_type VARCHAR(16),
    streetname TEXT,
    t_st TEXT,
    zip_code NUMERIC,
    slw_st NUMERIC,
    length NUMERIC,
    extents TEXT,
    status TEXT,
    phase NUMERIC,
    install_date TIMESTAMP,
    agency VARCHAR(16),
    type TEXT,
    supervisor_district VARCHAR(32),
    data_as_of TIMESTAMP,
    data_loaded_at TIMESTAMP
);