DROP TABLE IF EXISTS sf_streets_and_intersections_{suffix};
CREATE TABLE sf_streets_and_intersections_{suffix} (
    cnn INTEGER,
    lf_fadd SMALLINT,
    lf_toadd SMALLINT,
    rt_fadd SMALLINT,
    rt_toadd SMALLINT,
    street VARCHAR(32),
    st_type VARCHAR(8),
    f_st VARCHAR(64),
    t_st VARCHAR(64),
    f_node_cnn INTEGER,
    t_node_cnn INTEGER,
    accepted BOOLEAN,
    active BOOLEAN,
    classcode SMALLINT,
    date_added TIMESTAMP,
    date_altered TIMESTAMP,
    date_dropped TIMESTAMP,
    gds_chg_id_add VARCHAR(32),
    gds_chg_id_altered VARCHAR(32),
    gds_chg_id_dropped VARCHAR(32),
    jurisdiction VARCHAR(8),
    layer VARCHAR(32),
    nhood VARCHAR(32),
    oneway VARCHAR(4),
    street_gc VARCHAR(32),
    streetname VARCHAR(32),
    streetname_gc VARCHAR(32),
    zip_code INTEGER,
    analysis_neighborhood VARCHAR(32),
    supervisor_district VARCHAR(32),
    line geometry(LineString, 4326),
    data_as_of TIMESTAMP,
    data_loaded_at TIMESTAMP
);