/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapAreaViewRouteImport } from './routes/map-area-view'
import { Route as IndexRouteImport } from './routes/index'

const MapAreaViewRoute = MapAreaViewRouteImport.update({
  id: '/map-area-view',
  path: '/map-area-view',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map-area-view': typeof MapAreaViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map-area-view': typeof MapAreaViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map-area-view': typeof MapAreaViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map-area-view'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map-area-view'
  id: '__root__' | '/' | '/map-area-view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapAreaViewRoute: typeof MapAreaViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map-area-view': {
      id: '/map-area-view'
      path: '/map-area-view'
      fullPath: '/map-area-view'
      preLoaderRoute: typeof MapAreaViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapAreaViewRoute: MapAreaViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
