/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AreaViewRouteImport } from './routes/area-view'
import { Route as IndexRouteImport } from './routes/index'

const AreaViewRoute = AreaViewRouteImport.update({
  id: '/area-view',
  path: '/area-view',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-view': typeof AreaViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-view': typeof AreaViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-view': typeof AreaViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/area-view'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/area-view'
  id: '__root__' | '/' | '/area-view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaViewRoute: typeof AreaViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/area-view': {
      id: '/area-view'
      path: '/area-view'
      fullPath: '/area-view'
      preLoaderRoute: typeof AreaViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaViewRoute: AreaViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
