#!/bin/bash

set -e

# Perform all actions as $POSTGRES_USER
export PGUSER="$POSTGRES_USER"

# Load PostGIS into both template_database and $POSTGRES_DB
echo "Loading PostGIS extensions into $POSTGRES_DB"
"${psql[@]}" --dbname="$POSTGRES_DB" <<-'EOSQL'
CREATE TABLE IF NOT EXISTS sf_traffic_crashes_data_20250729_raw (
  unique_id TEXT,
  cnn_intrsctn_fkey INTEGER,
  cnn_sgmt_fkey INTEGER,
  case_id_pkey TEXT,
  tb_latitude DOUBLE PRECISION,
  tb_longitude DOUBLE PRECISION,
  geocode_source TEXT,
  geocode_location TEXT,
  collision_datetime TIMESTAMP,
  collision_date TIMESTAMP,
  collision_time TEXT,
  accident_year TEXT,
  month TEXT,
  day_of_week TEXT,
  time_cat TEXT,
  juris TEXT,
  officer_id TEXT,
  reporting_district TEXT,
  beat_number TEXT,
  primary_rd TEXT,
  secondary_rd TEXT,
  distance SMALLINT,
  direction TEXT,
  weather_1 TEXT,
  weather_2 TEXT,
  collision_severity TEXT,
  type_of_collision TEXT,
  mviw TEXT,
  ped_action TEXT,
  road_surface TEXT,
  road_cond_1 TEXT,
  road_cond_2 TEXT,
  lighting TEXT,
  control_device TEXT,
  intersection TEXT,
  vz_pcf_code TEXT,
  vz_pcf_group TEXT,
  vz_pcf_description TEXT,
  vz_pcf_link TEXT,
  number_killed DOUBLE PRECISION,
  number_injured DOUBLE PRECISION,
  street_view TEXT,
  dph_col_grp TEXT,
  dph_col_grp_description TEXT,
  party_at_fault TEXT,
  party1_type TEXT,
  party1_dir_of_travel TEXT,
  party1_move_pre_acc TEXT,
  party2_type TEXT,
  party2_dir_of_travel TEXT,
  party2_move_pre_acc TEXT,
  point geometry(Point, 4326),
  data_as_of TIMESTAMP,
  data_updated_at TIMESTAMP,
  data_loaded_at TIMESTAMP,
  analysis_neighborhood TEXT,
  supervisor_district TEXT,
  police_district TEXT,
  current_police_districts SMALLINT,
  current_supervisor_districts SMALLINT,
  analysis_neighborhoods SMALLINT,
  neighborhoods SMALLINT,
  sf_find_neighborhoods SMALLINT
);

CREATE TABLE IF NOT EXISTS sf_speed_limits_per_street_segment_20250729_raw (
  objectid              VARCHAR(64),
  cnn                   INTEGER,
  street                VARCHAR(64),
  st_type               VARCHAR(8),
  from_st               VARCHAR(64),
  to_st                 VARCHAR(64),
  speedlimit            SMALLINT,
  schoolzone            VARCHAR(8),
  schoolzone_limit      SMALLINT,
  mtab_date             TIMESTAMP,
  mtab_motion           VARCHAR(32),
  mtab_reso_text        VARCHAR(32),
  status                VARCHAR(32),
  workorder             VARCHAR(16),
  install_date          TIMESTAMP,
  shape                 geometry(MultiLineString, 4326),
  data_as_of            TIMESTAMP,
  data_loaded_at        TIMESTAMP,
  analysis_neighborhood VARCHAR(64),
  supervisor_district   VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS sf_streets_active_and_retired_streets_20250730_raw (
  cnn                    INTEGER,
  lf_fadd                SMALLINT,
  lf_toadd               SMALLINT,
  rt_fadd                SMALLINT,
  rt_toadd               SMALLINT,
  street                 VARCHAR(32),
  st_type                VARCHAR(8),
  f_st                   VARCHAR(64),
  t_st                   VARCHAR(64),
  f_node_cnn             INTEGER,
  t_node_cnn             INTEGER,
  accepted               BOOLEAN,
  active                 BOOLEAN,
  classcode              SMALLINT,
  date_added             TIMESTAMP,
  date_altered           TIMESTAMP,
  date_dropped           TIMESTAMP,
  gds_chg_id_add         VARCHAR(32),
  gds_chg_id_altered     VARCHAR(32),
  gds_chg_id_dropped     VARCHAR(32),
  jurisdiction           VARCHAR(8),
  layer                  VARCHAR(32),
  nhood                  VARCHAR(32),
  oneway                 VARCHAR(4),
  street_gc              VARCHAR(32),
  streetname             VARCHAR(32),
  streetname_gc          VARCHAR(32),
  zip_code               INT,
  analysis_neighborhood  VARCHAR(32),
  supervisor_district    SMALLINT,
  line                   geometry(LineString, 4326),
  data_as_of             TIMESTAMP,
  data_loaded_at         TIMESTAMP
);

COPY sf_speed_limits_per_street_segment_20250729_raw FROM '/initdata/sf_speed_limits_per_street_segment_20250729_raw.csv' DELIMITER ',' CSV HEADER;
COPY sf_streets_active_and_retired_streets_20250730_raw FROM '/initdata/sf_streets_active_and_retired_streets_20250730_raw.csv' DELIMITER ',' CSV HEADER;
COPY sf_traffic_crashes_data_20250729_raw FROM '/initdata/sf_traffic_crashes_data_20250729_raw.csv' DELIMITER ',' CSV HEADER;

EOSQL
