WITH data_to_add AS (
SELECT
    unique_id,
    cnn_intrsctn_fkey,
    cnn_sgmt_fkey,
    case_id_pkey,
    tb_latitude,
    tb_longitude,
    geocode_source,
    geocode_location,
    collision_datetime,
    collision_date,
    collision_time,
    accident_year,
    month,
    day_of_week,
    time_cat,
    juris,
    officer_id,
    reporting_district,
    beat_number,
    primary_rd,
    secondary_rd,
    distance,
    direction,
    weather_1,
    weather_2,
    collision_severity,
    type_of_collision,
    mviw,
    ped_action,
    road_surface,
    road_cond_1,
    road_cond_2,
    lighting,
    control_device,
    intersection,
    vz_pcf_code,
    vz_pcf_group,
    vz_pcf_description,
    vz_pcf_link,
    number_killed,
    number_injured,
    street_view,
    dph_col_grp,
    dph_col_grp_description,
    party_at_fault,
    party1_type,
    party1_dir_of_travel,
    party1_move_pre_acc,
    party2_type,
    party2_dir_of_travel,
    party2_move_pre_acc,
    point,
    data_as_of,
    data_updated_at,
    data_loaded_at,
    analysis_neighborhood,
    supervisor_district,
    police_district
FROM
    {data_table_name}
)
INSERT INTO sf_events(
    occured_at,
    event_type,
    cnn,
    point,
    metadata
)
SELECT
    collision_datetime as occured_at,
    'traffic_crash_resulting_in_injury' as event_type,
    CASE WHEN cnn_sgmt_fkey IS NULL THEN cnn_intrsctn_fkey ELSE cnn_sgmt_fkey END as cnn,
    dta.point as point,
    json_build_object(
        'unique_id', unique_id,
        'case_id_pkey', case_id_pkey,
        'tb_latitude', tb_latitude,
        'tb_longitude', tb_longitude,
        'geocode_source', geocode_source,
        'geocode_location', geocode_location,
        'day_of_week', day_of_week,
        'time_cat', time_cat,
        'juris', juris,
        'officer_id', officer_id,
        'reporting_district', reporting_district,
        'beat_number', beat_number,
        'primary_rd', primary_rd,
        'secondary_rd', secondary_rd,
        'distance', distance,
        'direction', direction,
        'weather_1', weather_1,
        'weather_2', weather_2,
        'collision_severity', collision_severity,
        'type_of_collision', type_of_collision,
        'mviw', mviw,
        'ped_action', ped_action,
        'road_surface', road_surface,
        'road_cond_1', road_cond_1,
        'road_cond_2', road_cond_2,
        'lighting', lighting,
        'control_device', control_device,
        'intersection', intersection,
        'vz_pcf_code', vz_pcf_code,
        'vz_pcf_group', vz_pcf_group,
        'vz_pcf_description', vz_pcf_description,
        'vz_pcf_link', vz_pcf_link,
        'number_killed', number_killed,
        'number_injured', number_injured,
        'street_view', street_view,
        'dph_col_grp', dph_col_grp,
        'dph_col_grp_description', dph_col_grp_description,
        'party_at_fault', party_at_fault,
        'party1_type', party1_type,
        'party1_dir_of_travel', party1_dir_of_travel,
        'party1_move_pre_acc', party1_move_pre_acc,
        'party2_type', party2_type,
        'party2_dir_of_travel', party2_dir_of_travel,
        'party2_move_pre_acc', party2_move_pre_acc,
        'data_as_of', data_as_of,
        'data_updated_at', data_updated_at,
        'data_loaded_at', data_loaded_at,
        'analysis_neighborhood', analysis_neighborhood,
        'supervisor_district', supervisor_district,
        'police_district', police_district
    ) as metadata
FROM
    data_to_add as dta
    LEFT JOIN 
    sf_events ON dta.unique_id = sf_events.metadata->>'unique_id'
WHERE
    sf_events.metadata->>'unique_id' IS NULL
;

UPDATE sf_events AS sfe
SET 
    occured_at = collision_datetime,
    cnn = CASE WHEN cnn_sgmt_fkey IS NULL THEN cnn_intrsctn_fkey ELSE cnn_sgmt_fkey END,
    point = dtu.point,
    metadata = json_build_object(
        'unique_id', unique_id,
        'case_id_pkey', case_id_pkey,
        'tb_latitude', tb_latitude,
        'tb_longitude', tb_longitude,
        'geocode_source', geocode_source,
        'geocode_location', geocode_location,
        'day_of_week', day_of_week,
        'time_cat', time_cat,
        'juris', juris,
        'officer_id', officer_id,
        'reporting_district', reporting_district,
        'beat_number', beat_number,
        'primary_rd', primary_rd,
        'secondary_rd', secondary_rd,
        'distance', distance,
        'direction', direction,
        'weather_1', weather_1,
        'weather_2', weather_2,
        'collision_severity', collision_severity,
        'type_of_collision', type_of_collision,
        'mviw', mviw,
        'ped_action', ped_action,
        'road_surface', road_surface,
        'road_cond_1', road_cond_1,
        'road_cond_2', road_cond_2,
        'lighting', lighting,
        'control_device', control_device,
        'intersection', intersection,
        'vz_pcf_code', vz_pcf_code,
        'vz_pcf_group', vz_pcf_group,
        'vz_pcf_description', vz_pcf_description,
        'vz_pcf_link', vz_pcf_link,
        'number_killed', number_killed,
        'number_injured', number_injured,
        'street_view', street_view,
        'dph_col_grp', dph_col_grp,
        'dph_col_grp_description', dph_col_grp_description,
        'party_at_fault', party_at_fault,
        'party1_type', party1_type,
        'party1_dir_of_travel', party1_dir_of_travel,
        'party1_move_pre_acc', party1_move_pre_acc,
        'party2_type', party2_type,
        'party2_dir_of_travel', party2_dir_of_travel,
        'party2_move_pre_acc', party2_move_pre_acc,
        'data_as_of', data_as_of,
        'data_updated_at', data_updated_at,
        'data_loaded_at', data_loaded_at,
        'analysis_neighborhood', analysis_neighborhood,
        'supervisor_district', supervisor_district,
        'police_district', police_district
    )
FROM
  {data_table_name} as dtu
WHERE
  sfe.metadata->>'unique_id' = dtu.unique_id
  AND (
    sfe.occured_at != dtu.collision_datetime OR
    (cnn != CASE WHEN dtu.cnn_sgmt_fkey IS NULL THEN COALESCE(dtu.cnn_intrsctn_fkey, 0) ELSE COALESCE(dtu.cnn_sgmt_fkey, 0) END) OR
    NOT ST_OrderingEquals(sfe.point, dtu.point) OR
    sfe.metadata::JSONB != json_build_object(
        'unique_id', unique_id,
        'case_id_pkey', case_id_pkey,
        'tb_latitude', tb_latitude,
        'tb_longitude', tb_longitude,
        'geocode_source', geocode_source,
        'geocode_location', geocode_location,
        'day_of_week', day_of_week,
        'time_cat', time_cat,
        'juris', juris,
        'officer_id', officer_id,
        'reporting_district', reporting_district,
        'beat_number', beat_number,
        'primary_rd', primary_rd,
        'secondary_rd', secondary_rd,
        'distance', distance,
        'direction', direction,
        'weather_1', weather_1,
        'weather_2', weather_2,
        'collision_severity', collision_severity,
        'type_of_collision', type_of_collision,
        'mviw', mviw,
        'ped_action', ped_action,
        'road_surface', road_surface,
        'road_cond_1', road_cond_1,
        'road_cond_2', road_cond_2,
        'lighting', lighting,
        'control_device', control_device,
        'intersection', intersection,
        'vz_pcf_code', vz_pcf_code,
        'vz_pcf_group', vz_pcf_group,
        'vz_pcf_description', vz_pcf_description,
        'vz_pcf_link', vz_pcf_link,
        'number_killed', number_killed,
        'number_injured', number_injured,
        'street_view', street_view,
        'dph_col_grp', dph_col_grp,
        'dph_col_grp_description', dph_col_grp_description,
        'party_at_fault', party_at_fault,
        'party1_type', party1_type,
        'party1_dir_of_travel', party1_dir_of_travel,
        'party1_move_pre_acc', party1_move_pre_acc,
        'party2_type', party2_type,
        'party2_dir_of_travel', party2_dir_of_travel,
        'party2_move_pre_acc', party2_move_pre_acc,
        'data_as_of', data_as_of,
        'data_updated_at', data_updated_at,
        'data_loaded_at', data_loaded_at,
        'analysis_neighborhood', analysis_neighborhood,
        'supervisor_district', supervisor_district,
        'police_district', police_district
    )::JSONB
);
